code/config/routes.rb
Rails.application.routes.draw do
  get '/search' => 'pages#search', :as => 'search_page'
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :articles
  root 'welcome#index'
end

code/app/models/application_record.rb
# This file WAS auto generated
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

code/app/models/article.rb
# Article titles may not be longer than 30 characters
class Article < ApplicationRecord
  validates :title, presence: true,
  		length: { maximum: 40 }
end

code/app/controllers/application_controller.rb
# This file WAS auto generated

# Application controller will inherit from action controller by default
class ApplicationController < ActionController::Base
end

code/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	http_basic_authenticate_with name: "admin", password: "password", except: [:index, :show]

	def index
		@articles = Article.all
	end

	def show
		@article = Article.find(params[:id])
    end

	def new
		@article = Article.new
	end

	def edit
		@article = Article.find(params[:id])
	end

	def create
		@article = Article.new(article_params)

		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def update
		@article = Article.find(params[:id])
		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		
		redirect_to articles_path
	end

	private
	def article_params
		params.require(:article).permit(:title, :text)
	end
end

code/app/controllers/pages_controller.rb
# Pages controller inherits from the application controller
class PagesController < ApplicationController

# Searching is handled by this controller
def search  
# If the user searches for a blank entry, they will be redirected to the welcome page
  if params[:search].blank?  
    redirect_to('/welcome/index', alert: "Please enter a search term") and return  
# If the user searches for an entry, their search will be converted to lowercase
  else  
    @parameter = params[:search].downcase  
    @results = Article.all.where("lower(Title) LIKE :search", search: "%#{@parameter}%")  
  end     
end

end

code/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

code/app/helpers/application_helper.rb
module ApplicationHelper
end

code/app/helpers/articles_helper.rb
module ArticlesHelper
end

code/app/helpers/pages_helper.rb
module PagesHelper
end

code/app/helpers/welcome_helper.rb
module WelcomeHelper
end

code/app/views/articles/_form.html.erb
<!-- This file was NOT auto generated -->

<%= form_with model: @article, local: true do |form| %>
<!-- Checking that adding an article is done so correctly (can't have blank title or text field) -->
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<!-- Form submission has a title, text, and submit button --> 
  <p>
    <%= form.label :title %>&nbsp;<br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %>&nbsp;<br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

code/app/views/articles/edit.html.erb
<!-- This file was NOT auto generated -->

<!-- Editing an article will render the form and the link to go back -->
<h1>Edit article</h1>
<%= render 'form' %>
<%= link_to 'Back', articles_path %>

code/app/views/articles/index.html.erb
<!-- This file was NOT auto generated -->

<!-- App logo -->
<a href="/welcome/index">
<img src="https://image.ibb.co/ccBNDA/testing.jpg" alt="Potential Brain Wave logo" border="0">
</a>

<!-- Creating header "Articles" -->
<h1>Articles</h1>

<!-- Adding ability to search on this page (in the middle of the page at the top) -->
<div align = center>
<%= form_tag(search_page_path, :method => "get",   
class: 'navbar-form navbar-left') do %>  
<div class="input-group" align="center">  
<%= search_field_tag :search, params[:search], placeholder: "Search topics here", class: "form-control" %>  
  <%= button_tag "Search",:name => nil%>  
</div>  
<% end %> 
</div>

<!-- Clicking on Create an Article here will lead to the new article path -->
<%= link_to 'Create an Article', new_article_path %>

<!-- Defining style for table borders -->
<style>
table, th, td {
    border: 1px solid black;
}
</style>

<!-- Articles will be put in table with Title, View, Edit, Delete headers -->
<table style="width:100%">
  <tr>
    <th>Title</th>
    <th>View</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>

<!-- Rendering each article into table. View, Edit, Delete will be dependant on that article's path -->
  <% @articles.each do |article| %>
    <tr>
      <td style="text-align: center"><%= article.title %>&nbsp;</td>
<!--       <td><%= article.text %>&nbsp;</td>
 -->      <td style="text-align: center"><%= link_to 'View', article_path(article) %></td>
      <td style="text-align: center"><%= link_to 'Edit', article_path(article) %></td>
   <!-- If request for deletion is made, confirmation box (rendered by browswer) must be completed -->
      <td style="text-align: center"><%= link_to 'Delete', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

code/app/views/articles/new.html.erb
<!-- This file was NOT auto generated -->

<!-- App logo -->
<a href="/welcome/index">
<img src="https://image.ibb.co/ccBNDA/testing.jpg" alt="Potential Brain Wave logo" border="0">
</a>

<!-- Create an Article header -->
<h1>Create An Article</h1>
<!-- Creating an article will render the form and link to go back -->
<%= render 'form' %>
<%= link_to 'Back', articles_path %>

code/app/views/articles/show.html.erb
<!-- This file was NOT auto generated -->

<!-- App logo -->
<a href="/welcome/index">
<img src="https://image.ibb.co/ccBNDA/testing.jpg" alt="Potential Brain Wave logo" border="0">
</a>

<!-- Defining style for showing text -->
<style>
	div {
		word-break: break-all;
		text-align: justify;
	}
</style>

<!-- Showing the article's title -->
<p>
  <strong>Title:&nbsp;</strong> 
  <%= @article.title %>
</p>

<!-- Showing the article's text -->
<div>
<p>

  <strong>Text:</strong>
  <pre>
    <%= @article.text %>
  </pre>
</p>
</div>
 
 <!-- Edit will allow the article to be edited, back will return to the previous page -->
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

code/app/views/layouts/application.html.erb
<!-- This file WAS auto-generated -->

<!DOCTYPE html>
<html>
  <head>
    <title>Brain Wave</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

code/app/views/pages/explore.html.erb
<!-- 
// Name: Daniel Hanna 
// Course: CSC 415 
// Semester: Fall 2018
// Instructor: Dr. Pulimood 
// Project name: Brain Wave 
// Description: Application to aid students with educational inequality
// Filename: explore.html.erb
// Description: format/styling for the "Explore" page of the website
-->

<!DOCTYPE html>
<html>

<body>	
 	<a href="/pages/welcome"><img src="https://image.ibb.co/ccBNDA/testing.jpg" alt="Potential Brain Wave logo" border="0">		
 	<a href="/pages/welcome">Home</a>&nbsp;&nbsp;
	<a href="/pages/explore">Explore</a>&nbsp;&nbsp;
	<a href="/pages/help">Help</a>&nbsp;&nbsp;
	<h1>Explore</h1>
	<p>Check out our catalog of guides & tips below!</p>
	<p>(Articles, guides, etc would be populated here)
</body>
</html>

code/app/views/pages/help.html.erb
<!-- 
// Name: Daniel Hanna
// Course: CSC 415 
// Semester: Fall 2018
// Instructor: Dr. Pulimood 
// Project name: Brain Wave 
// Description: Application to aid students with educational inequality
// Filename: help.html.erb
// Description: format/styling for the "Help" page of the website
-->


<!DOCTYPE html>
<html>

<body>	
	<div id="Link Headings">
	<a href="/pages/welcome"><img src="https://image.ibb.co/ccBNDA/testing.jpg" alt="Potential Brain Wave logo" border="0">		
 	<a href="/pages/welcome">Home</a>&nbsp;&nbsp;
	<a href="/pages/explore">Explore</a>&nbsp;&nbsp;
	<a href="/pages/help">Help</a>&nbsp;&nbsp;
	</div>

	<h1>Help</h1>
	<p>Fill out the questionare below to have specific articles, guides, and tips recommended to you!</p>

	<div id="Entry Form">
		<form>
			<p>1. What type of person are you?</p>
			<input type="radio" name="title" value="student" checked>Student
			<input type="radio" name="title" value="parent">Parent
			<input type="radio" name="title" value="teacher">Teacher
			<input type="radio" name="title" value="other">Other<br>
			<p>2. Question 2 goes here</p>
			<p>3. Question 3 goes here, etc etc</p>
			<br><input type="submit" value="Submit">
			<form action="/action_page.php">
			</form>
		</div>

	</body>
	</html>

code/app/views/pages/search.html.erb
<!-- This file was NOT auto-generated -->

<!-- Defining style for tables to help with organization (and make the app look more pretty) -->
<style>
table, th, td {
	border: 1px solid black;
}
</style>

<!-- App logo -->
<a href="/welcome/index">
	<img src="https://image.ibb.co/ccBNDA/testing.jpg" alt="Potential Brain Wave logo" border="0">
</a>

<!-- Header -->
<h1>Article Search Results</h1> 

<!-- Putting instructions in their own sections -->
<table style="width:100%">
<p>Below is the results found for your search. Please note: A blank page means no results were found.</p>  
</table>

<!-- Running through each result and displaying the title with a link to view (showing the entire article would be too clustered) -->
<table style="width:100%">
<% @results.each do |result| %>
	<tr>
		<p><b>Article Name: </b><%= result.title %><br></p> 
		<p><b>Article Text: </b><%= link_to 'View', article_path(result) %><br></p>
	</tr>
</table>
<% end %>

code/app/views/pages/welcome.html.erb
<!-- 
// Name: Daniel Hanna 
// Course: CSC 415 
// Semester: Fall 2018
// Instructor: Dr. Pulimood 
// Project name: Brain Wave 
// Description: Application to aid students with educational inequality
// Filename: welcome.html.erb
// Description: format/styling for the "Welcome" page of the website
-->


<!DOCTYPE html>
<html>

<body>
	<a href="/pages/welcome"><img src="https://image.ibb.co/ccBNDA/testing.jpg" alt="Potential Brain Wave logo" border="0">		
 	<a href="/pages/welcome">Home</a>&nbsp;&nbsp;
	<a href="/pages/explore">Explore</a>&nbsp;&nbsp;
	<a href="/pages/help">Help</a>&nbsp;&nbsp;
	<h1>Welcome to Brain Wave</h1>
	<p>Brain Wave is a hub of various supplemental academic resources for all sorts of students. If you need help with something school related, check out the <a href="/pages/explore">Explore</a> section. If you're not sure where to start, click on <a href="/pages/help">Help</a> section, and fill out the questions!</p>
</body>
</html>

code/app/views/welcome/index.html.erb
<!-- This file was NOT auto-generated -->

<!-- Simple Logo that is implemented at the top of the app's pages -->
<a href="/welcome/index">
<img src="https://image.ibb.co/ccBNDA/testing.jpg" alt="Potential Brain Wave logo" border="0">
</a>

<!-- Header & Short Description -->
<h1>Welcome to Brain Wave</h1>
<p>Brain Wave is a hub of various supplemental academic resources for all sorts of students.<br><br>If you need help with something school related, check out the

<!-- Link to the list of articles -->
<font color="blue"><b><%= link_to 'list of articles', controller: 'articles' %></b></font>.<br><br>You can return to this homepage at any time by clicking on the logo at the top of each screen.<br><br>Search at any time from the search bar on the page.</p>

<!-- Search box which takes in a search entry and searchs list of articles through the pages_controller -->
<%= form_tag(search_page_path, :method => "get") do %>   
<%= search_field_tag :search, params[:search], placeholder: "Search topics here"%>  
  <%= button_tag "Search",:name => nil%>    
<% end %> 